### ISSUE TITLE
Auto Update checkbox resets after extension restart

### ISSUE THREAD

**Issue by tomasz-skarzynski** [danielboucek/private-extensions-gitlab#1]
When I enable the "Auto Update" checkbox, the extension detects and updates properly, but after restarting the extension, the checkbox becomes unchecked. This could be a misconfiguration on my end or possibly something related to VS Code itself, but I wanted to report it just in case.

**Comment by danielboucek** [comment]
Hi, thank you for reporting this. 

There is more than one "Auto Update" checkbox. The main one is located in the extension settings of this extension and controls the automatic updates of all installed extensions that are available through this extension. This one should be enabled by default.
![image](https://github.com/user-attachments/assets/0097512f-fb1c-43e1-baae-5f4576e4a0c5)

You probably mean the second "Auto Update" checkbox available for each extension separately. This is a recently added VS Code feature that works only with extensions in the official VS Marketplace and you can leave it unchecked. Since your private extensions are fetched from GitLab and handled with this extension.
![image](https://github.com/user-attachments/assets/aac8105e-9c7b-4f94-a703-6ecf444151af)

Let me know what you meant or if that answered your question.

**Comment by tomasz-skarzynski** [comment]
The mechanism works, and indeed that second checkbox right next to the plug-in preview is confusing. I suppose there is no control over it from the developer level to check it, e.g. in the package.json settings, because that would go beyond the plugin's permissions.
